### ISSUE TITLE
Status of project - Midterm suggestions - Terminated tasks

### ISSUE THREAD

**Issue by pacellig** [gtataranni/remote-access#10]
**ToDo or To be Improved/Terminated:**
- ~~Improve UI towards a chat interface~~ ✓done
  → All the functionalities completely moved to the new GUI
- batch mode 
  → for now, implemented it in linux style, by putting a ';' after the 'read/gps' so that you can write another /dest/read/something after that. 
  → adding the picture to the list of messages but it doesn't work. It's because of the communication model for the picture, maybe a list of pictures should be kept (?)
- periodic cmd 
  → a pubsub communication model
  → 1st version for GPS implemented , needs to be implemented also for the pictures (?)
- ~~persistent storage of the results~~
  → done for the photo, adding a gallery that shows the pictures
- formalize generic schemes on per service basis (photo, gps)
  → ENTIRELY To be written 
- ~~change the app name to "Drone Controller"~~

*\* Terminated tasks from the ones included in the midterm presentation: **
- ~~Show received GPS position on a map.~~                                              ✓done
- ~~Improve application connectivity by keeping a thread in background.~~ ✓done
- ~~Send GPS position through clicking on a map.~~                                   ✓done 
- ~~Let user to save pictures to memory.~~                                                   ✓done 
- ~~Stream video.~~                                                                                       ✓done

**Comment by gtataranni** [comment]
Moved the buttons to the new GUI done, so it's more user friendly now 😊

**Comment by gtataranni** [comment]
TODO: change the app name to "Drone Controller"
