### ISSUE TITLE
TODO: Save and load pictures from the storage

### ISSUE THREAD

**Issue by leoxama** [gtataranni/remote-access#5]
We have to manage to save pictures in the storage (done but not tested), show the pictures somehow and load them from the storage to be send to the server(change the input source -> it is not supposed to be difficult to implement)

**Comment by pacellig** [comment]
I implemented the possibility to save the picture.
don't know if the write is a feature that we really need

**Comment by gtataranni** [comment]
What do you mean by the write feature?

**Comment by pacellig** [comment]
sending a picture stored on the phone, instead of sending the picture as soon as it's taken ( the feature we have now )

**Comment by pacellig** [comment]
I've implemented the auto-save feature on the cache of the app. 
Now there is the activity 'GalleryActivity' that loads such pictures from the storage and shows them.
Needs to be improved and integrated in the new UI, but most of the work is done -> closing this issue.
